[ERROR] 2017-03-07 19:48:25.643 [main] MysqlWriter - Error occured when inserting Property: 
java.sql.SQLException: Data truncated for column 'useCode' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at main.java.dbConnectors.MysqlWriter.insertObject(MysqlWriter.java:234) [classes/:?]
	at main.java.classes_for_db.Property.writeToDB(Property.java:1417) [classes/:?]
	at main.java.execute.Executor.getDataForAddress(Executor.java:123) [classes/:?]
	at main.java.execute.Executor.run(Executor.java:68) [classes/:?]
	at main.java.execute.Main.main(Main.java:55) [classes/:?]
[ERROR] 2017-03-07 19:48:28.161 [main] MysqlWriter - Error occured when inserting Property: 
java.sql.SQLException: Data truncated for column 'useCode' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at main.java.dbConnectors.MysqlWriter.insertObject(MysqlWriter.java:234) [classes/:?]
	at main.java.classes_for_db.Property.writeToDB(Property.java:1417) [classes/:?]
	at main.java.execute.Executor.getDataForAddress(Executor.java:123) [classes/:?]
	at main.java.execute.Executor.run(Executor.java:68) [classes/:?]
	at main.java.execute.Main.main(Main.java:55) [classes/:?]
[ERROR] 2017-03-07 19:48:30.518 [main] MysqlWriter - Error occured when inserting Property: 
java.sql.SQLException: Data truncated for column 'useCode' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at main.java.dbConnectors.MysqlWriter.insertObject(MysqlWriter.java:234) [classes/:?]
	at main.java.classes_for_db.Property.writeToDB(Property.java:1417) [classes/:?]
	at main.java.execute.Executor.getDataForAddress(Executor.java:123) [classes/:?]
	at main.java.execute.Executor.run(Executor.java:68) [classes/:?]
	at main.java.execute.Main.main(Main.java:55) [classes/:?]
[ERROR] 2017-03-07 20:15:23.990 [main] MysqlWriter - Error occured when inserting Property: 
java.sql.SQLException: Column index out of range.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:896) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:885) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.ResultSetMetaData.getField(ResultSetMetaData.java:395) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.ResultSetMetaData.getColumnLabel(ResultSetMetaData.java:224) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at main.java.dbConnectors.MysqlWriter.insertObject(MysqlWriter.java:205) [classes/:?]
	at main.java.classes_for_db.Property.writeToDB(Property.java:1417) [classes/:?]
	at main.java.execute.Executor.getDataForAddress(Executor.java:123) [classes/:?]
	at main.java.execute.Executor.run(Executor.java:68) [classes/:?]
	at main.java.execute.Main.main(Main.java:55) [classes/:?]
[ERROR] 2017-03-07 20:17:16.976 [main] MysqlWriter - Error occured when inserting Property: 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2119249872' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:932) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at main.java.dbConnectors.MysqlWriter.insertObject(MysqlWriter.java:234) [classes/:?]
	at main.java.classes_for_db.Property.writeToDB(Property.java:1417) [classes/:?]
	at main.java.execute.Executor.getDataForAddress(Executor.java:123) [classes/:?]
	at main.java.execute.Executor.run(Executor.java:68) [classes/:?]
	at main.java.execute.Main.main(Main.java:55) [classes/:?]
[ERROR] 2017-03-07 20:17:19.225 [main] MysqlWriter - Error occured when inserting Property: 
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2119249872' for key 'PRIMARY'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:932) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192) ~[mysql-connector-java-5.1.38-bin.jar:5.1.38]
	at main.java.dbConnectors.MysqlWriter.insertObject(MysqlWriter.java:234) [classes/:?]
	at main.java.classes_for_db.Property.writeToDB(Property.java:1417) [classes/:?]
	at main.java.execute.Executor.getDataForAddress(Executor.java:123) [classes/:?]
	at main.java.execute.Executor.run(Executor.java:68) [classes/:?]
	at main.java.execute.Main.main(Main.java:55) [classes/:?]
